### ISSUE TITLE
[Tooling] Work out a better way to build

### ISSUE THREAD

**Issue by ojkelly** [KablamoOSS/kerosene#21]
```
     "prebuild": "yarn workspace @kablamo/kerosene run build", 
```

is required because `kerosene-ui` depends on `kerosene`.

Is there a better way to do this? We should be able to keep the build system to a single command.

**Comment by nhardy** [comment]
`@kablamo/kerosene-ui` actually doesn't depend on the local copy of `@kablamo/kerosene`, but it seems like the TS typings do depend on the local version (which get deleted when the clean step is run). From what I can tell, there doesn't seem to be a way to control the order that packages build in.
